- name: wait all node ready
  command: kubectl get nodes -o=json
  register: kubectl_get_nodes
  until:
    - kubectl_get_nodes.stdout | from_json | json_query('items') | length == groups['k3s_agents'] | length + groups['k3s_ha_servers'] | length + 1
    - kubectl_get_nodes.stdout | from_json | json_query('items[*].status.conditions[?type==`Ready`].status') | unique == [[ "True" ]]
  retries: 180
  delay: 1
