---
- name: gather the package facts
  package_facts:
    manager: auto

- include_tasks: docker.yaml
  when: (ansible_facts.packages['docker-ce'] is not defined) or
    (ansible_facts.packages['docker-ce-cli'] is not defined)

- name: check docker-compose version
  command: docker-compose -v
  register: compose_version
  failed_when: false

- include_tasks: compose.yaml
  when: compose_version.stdout is not defined

- name: check mongo
  command: docker inspect m-0 m-1 m-2
  register: docker_inspect_mongo
  failed_when: false

- include_tasks: mongo.yaml
  when: docker_inspect_mongo.stdout | from_json | json_query('[]') | length != 3

- name: check mysql
  command: docker inspect mysql
  register: docker_inspect_mysql
  failed_when: false

- include_tasks: mysql.yaml
  when: docker_inspect_mysql.stdout | from_json | json_query('[]') | length != 1

- name: check redis
  command: docker inspect redis
  register: docker_inspect_redis
  failed_when: false

- include_tasks: redis.yaml
  when: docker_inspect_redis.stdout | from_json | json_query('[]') | length != 1