---
- name: create docker vol folder
  become: yes
  file:
    path: "{{ docker_vol_path }}/mysql/data"
    state: directory

- name: create compose folder
  file:
    path: ./mysql
    state: directory

- name: copy compose
  copy:
    src: mysql/docker-compose.yaml
    dest: ./mysql/docker-compose.yaml

- name: copy mysql config
  become: yes
  copy:
    src: mysql/my.cnf
    dest: "{{ docker_vol_path }}/mysql/my.cnf"

- name: modify docker volume path
  replace:
    path: mysql/docker-compose.yaml
    regexp: "DOCKER_VOL_PATH"
    replace: "{{ docker_vol_path }}"

- name: start mysql
  command: docker-compose up -d
  args:
    chdir: mysql/

- name: wait mysql healthy
  command: docker inspect mysql
  register: docker_inspect
  until: docker_inspect.stdout | from_json | json_query('[*].State.Health.Status') == [ "healthy" ]
  retries: 180
  delay: 1
